version: '3.3'
services:
  nginx:
    image: nginx:1.13.6-alpine
    restart: always
    volumes:
      - ./codebase:/opt/pickem-releases
      - ./docker/nginx/watchpoint.conf:/etc/nginx/conf.d/watchpoint.conf
    ports:
      - 80
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: always
    volumes:
      - ./codebase:/opt/pickem-releases
    ports:
      - 9000
