version: '3.3'
services:
  dev-ssl:
    build:
      context: .
      dockerfile: docker/dev-ssl/Dockerfile
    restart: "no"
    volumes:
      - ./data/ssl/certs:/etc/ssl/certs/watchpoint
      - ./docker/dev-ssl/docker-entrypoint.sh:/docker-entrypoint.sh
