version: '3.3'
services:
  nginx:
    image: nginx:1.13.6-alpine
    restart: always
    volumes:
      - ./codebase:/opt/pickem-releases
      - ./data/ssl/certs:/etc/ssl/certs/watchpoint
      - ./data/ssl/letsencrypt/.well-known:/opt/letsencrypt/.well-known
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80
      - 443
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: always
    volumes:
      - ./codebase:/opt/pickem-releases
    ports:
      - 9000
    environment:
      DB_URL: "${DB_URL}"
      BNET_API_KEY: "${BNET_API_KEY}"
      BNET_API_SECRET: "${BNET_API_SECRET}"
